version: "3.8"

services:
  auth-service:
    build: ./Backend/auth-service
    env_file:
      - ./Backend/auth-service/.env
    restart: always

  media-service:
    build: ./Backend/media-service
    env_file:
      - ./Backend/media-service/.env
    restart: always

  post-service:
    build: ./Backend/post-service
    env_file:
      - ./Backend/post-service/.env
    restart: always

  user-service:
    build: ./Backend/user-service
    env_file:
      - ./Backend/user-service/.env
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - user-service
      - post-service
      - media-service
    restart: always
