server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth-service:3001/;
    }

    location /media/ {
        proxy_pass http://media-service:3002/;
    }

    location /post/ {
        proxy_pass http://post-service:3003/;
    }

    location /user/ {
        proxy_pass http://user-service:3004/;
    }

    # Default route
    location / {
        proxy_pass http://user-service:3004;
    }
}
