sonar.projectKey=insta-project
sonar.sources=Backend,Frontend
sonar.exclusions=node_modules/**,build/**,dist/**
sonar.host.url=http://localhost:9000
sonar.login=sqp_742a9a013ecbe18aab2210c57879ab4dc9a5718e
