apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa-custom
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service

  minReplicas: 2
  maxReplicas: 10

  metrics:
  - type: Pods
    pods:
      metric:
        name: promhttp_metric_handler_requests
      target:
        type: AverageValue
        averageValue: 10
