apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: media-service-monitor
  labels:
    release: monitoring   # VERY IMPORTANT (matches Prometheus)
spec:
  selector:
    matchLabels:
      app: media-service   # MUST match service labels

  endpoints:
    - port: http           # MUST match service port name
      path: /metrics
      interval: 10s
