apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: post-service-monitor
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: post-service

  namespaceSelector:
    matchNames:
      - default

  endpoints:
  - port: http
    path: /metrics
    interval: 15s
