apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: media-scaler
  namespace: default

spec:
  scaleTargetRef:
    name: media-service

  minReplicaCount: 2
  maxReplicaCount: 10

  pollingInterval: 15
  cooldownPeriod: 60

  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
      metricName: media_rps
      query: sum(rate(http_requests_total{service="media-service"}[1m]))
      threshold: "100"
