{
 "title": "Insta Project Auto Scaling",
 "panels": [
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "User Service RPS",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service=\"user-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pod Scaling",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas"
    }
   ]
  },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[1m])) by (pod)"
    }
   ]
  }
 ]
}